# Generated by Django 5.2.13 on 2026-04-22 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attacco',
            fields=[
                ('id_attacco', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('descrizione', models.TextField()),
                ('severita', models.CharField(choices=[('bassa', 'Bassa'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Critica')], max_length=10)),
                ('data_pubblicazione', models.DateField()),
                ('riferimento_mitre', models.CharField(blank=True, max_length=50)),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='attacchi_img/')),
            ],
            options={
                'db_table': 'attacco',
            },
        ),
        migrations.CreateModel(
            name='Contromisura',
            fields=[
                ('id_contromisura', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('descrizione', models.TextField()),
                ('tipo', models.CharField(choices=[('preventiva', 'Preventiva'), ('rilevativa', 'Rilevativa'), ('correttiva', 'Correttiva')], max_length=12)),
            ],
            options={
                'db_table': 'contromisura',
            },
        ),
        migrations.CreateModel(
            name='Utenti',
            fields=[
                ('id_utente', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('data_registrazione', models.DateField(auto_now_add=True)),
                ('livello', models.IntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('foto_profilo', models.ImageField(blank=True, null=True, upload_to='profili/')),
            ],
            options={
                'db_table': 'utenti',
            },
        ),
        migrations.CreateModel(
            name='AttaccoMalware',
            fields=[
                ('attacco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='malware', serialize=False, to='core.attacco')),
                ('tipo_payload', models.CharField(max_length=50)),
                ('persistenza', models.BooleanField(default=False)),
                ('propagazione', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'attacco_malware',
            },
        ),
        migrations.CreateModel(
            name='AttaccoRete',
            fields=[
                ('attacco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rete', serialize=False, to='core.attacco')),
                ('protocollo', models.CharField(max_length=20)),
                ('porta_bersaglio', models.IntegerField(blank=True, null=True)),
                ('livello_osi', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'attacco_rete',
            },
        ),
        migrations.CreateModel(
            name='AttaccoSocial',
            fields=[
                ('attacco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='social', serialize=False, to='core.attacco')),
                ('canale', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('telefono', 'Telefono'), ('social', 'Social Media')], max_length=20)),
                ('leva_psicologica', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'attacco_social',
            },
        ),
        migrations.CreateModel(
            name='AttaccoWeb',
            fields=[
                ('attacco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='web', serialize=False, to='core.attacco')),
                ('tipo_injection', models.CharField(max_length=50)),
                ('owasp_category', models.CharField(choices=[('A01', 'A01'), ('A02', 'A02'), ('A03', 'A03'), ('A04', 'A04'), ('A05', 'A05'), ('A06', 'A06'), ('A07', 'A07'), ('A08', 'A08'), ('A09', 'A09'), ('A10', 'A10')], max_length=10)),
                ('url_esempio', models.URLField(blank=True)),
            ],
            options={
                'db_table': 'attacco_web',
            },
        ),
        migrations.CreateModel(
            name='CasoReale',
            fields=[
                ('id_caso', models.AutoField(primary_key=True, serialize=False)),
                ('nome_incidente', models.CharField(max_length=200)),
                ('anno', models.IntegerField()),
                ('vittima', models.CharField(max_length=200)),
                ('danno_stimato_usd', models.BigIntegerField(blank=True, null=True)),
                ('descrizione_breve', models.TextField()),
                ('id_attacco', models.ForeignKey(db_column='id_attacco', on_delete=django.db.models.deletion.PROTECT, related_name='casi_reali', to='core.attacco')),
            ],
            options={
                'db_table': 'caso_reale',
            },
        ),
        migrations.CreateModel(
            name='Interazione',
            fields=[
                ('id_interazione', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('like', 'Like'), ('commento', 'Commento'), ('segnalazione', 'Segnalazione')], max_length=12)),
                ('testo_commento', models.TextField(blank=True, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('id_utente', models.ForeignKey(db_column='id_utente', on_delete=django.db.models.deletion.CASCADE, related_name='interazioni', to='core.utenti')),
            ],
            options={
                'db_table': 'interazione',
            },
        ),
        migrations.AddField(
            model_name='attacco',
            name='id_autore',
            field=models.ForeignKey(db_column='id_autore', on_delete=django.db.models.deletion.PROTECT, related_name='attacchi', to='core.utenti'),
        ),
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id_articolo', models.AutoField(primary_key=True, serialize=False)),
                ('titolo', models.CharField(max_length=300)),
                ('testo', models.TextField()),
                ('data_pubblicazione', models.DateField(auto_now_add=True)),
                ('id_autore', models.ForeignKey(db_column='id_autore', on_delete=django.db.models.deletion.PROTECT, related_name='articoli', to='core.utenti')),
            ],
            options={
                'db_table': 'articolo',
            },
        ),
        migrations.CreateModel(
            name='Vulnerabilita',
            fields=[
                ('id_vulnerabilita', models.AutoField(primary_key=True, serialize=False)),
                ('codice_cve', models.CharField(db_index=True, max_length=20, unique=True)),
                ('descrizione', models.TextField()),
                ('cvss_score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('software_affetto', models.CharField(max_length=200)),
                ('anno_scoperta', models.IntegerField(db_index=True)),
            ],
            options={
                'db_table': 'vulnerabilita',
                'constraints': [models.CheckConstraint(condition=models.Q(('cvss_score__gte', 0), ('cvss_score__lte', 10)), name='cvss_range'), models.CheckConstraint(condition=models.Q(('anno_scoperta__gte', 1980)), name='anno_scoperta_min')],
            },
        ),
        migrations.CreateModel(
            name='InterazioneArticolo',
            fields=[
                ('interazione', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='articolo_target', serialize=False, to='core.interazione')),
                ('id_articolo', models.ForeignKey(db_column='id_articolo', on_delete=django.db.models.deletion.CASCADE, related_name='interazioni', to='core.articolo')),
            ],
            options={
                'db_table': 'interazione_articolo',
            },
        ),
        migrations.CreateModel(
            name='InterazioneAttacco',
            fields=[
                ('interazione', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='attacco_target', serialize=False, to='core.interazione')),
                ('id_attacco', models.ForeignKey(db_column='id_attacco', on_delete=django.db.models.deletion.CASCADE, related_name='interazioni', to='core.attacco')),
            ],
            options={
                'db_table': 'interazione_attacco',
            },
        ),
        migrations.CreateModel(
            name='InterazioneCaso',
            fields=[
                ('interazione', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='caso_target', serialize=False, to='core.interazione')),
                ('id_caso', models.ForeignKey(db_column='id_caso', on_delete=django.db.models.deletion.CASCADE, related_name='interazioni', to='core.casoreale')),
            ],
            options={
                'db_table': 'interazione_caso',
            },
        ),
        migrations.CreateModel(
            name='Mitiga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efficacia', models.CharField(choices=[('bassa', 'Bassa'), ('media', 'Media'), ('alta', 'Alta')], max_length=6)),
                ('id_attacco', models.ForeignKey(db_column='id_attacco', on_delete=django.db.models.deletion.CASCADE, to='core.attacco')),
                ('id_contromisura', models.ForeignKey(db_column='id_contromisura', on_delete=django.db.models.deletion.CASCADE, to='core.contromisura')),
            ],
            options={
                'db_table': 'mitiga',
                'unique_together': {('id_contromisura', 'id_attacco')},
            },
        ),
        migrations.CreateModel(
            name='Seguito',
            fields=[
                ('id_seguito', models.AutoField(primary_key=True, serialize=False)),
                ('id_seguace', models.ForeignKey(db_column='id_seguace', on_delete=django.db.models.deletion.CASCADE, related_name='following', to='core.utenti')),
                ('id_utente_seguito', models.ForeignKey(db_column='id_utente_seguito', on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='core.utenti')),
            ],
            options={
                'db_table': 'seguito',
                'constraints': [models.CheckConstraint(condition=models.Q(('id_seguace', models.F('id_utente_seguito')), _negated=True), name='no_self_follow')],
                'unique_together': {('id_seguace', 'id_utente_seguito')},
            },
        ),
        migrations.CreateModel(
            name='Sfrutta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_attacco', models.ForeignKey(db_column='id_attacco', on_delete=django.db.models.deletion.CASCADE, to='core.attacco')),
                ('id_vulnerabilita', models.ForeignKey(db_column='id_vulnerabilita', on_delete=django.db.models.deletion.CASCADE, to='core.vulnerabilita')),
            ],
            options={
                'db_table': 'sfrutta',
                'unique_together': {('id_attacco', 'id_vulnerabilita')},
            },
        ),
    ]
